//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitchMemeAlertsAuto.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwitchMemeAlertsAuto.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutMenu {
            get {
                return ResourceManager.GetString("AboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &quot;Show last memer&quot; Reward.
        /// </summary>
        public static string AddShowMemer {
            get {
                return ResourceManager.GetString("AddShowMemer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on login.
        /// </summary>
        public static string AddWinStartup {
            get {
                return ResourceManager.GetString("AddWinStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance:.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string ConnectionsLabel {
            get {
                return ResourceManager.GetString("ConnectionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectLabel {
            get {
                return ResourceManager.GetString("ConnectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to MemeAlerts.
        /// </summary>
        public static string ConnectMemeAlertsTooltip {
            get {
                return ResourceManager.GetString("ConnectMemeAlertsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Twitch.
        /// </summary>
        public static string ConnectTwitchTooltip {
            get {
                return ResourceManager.GetString("ConnectTwitchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day before yesterday.
        /// </summary>
        public static string DayBeforeYesterday {
            get {
                return ResourceManager.GetString("DayBeforeYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while issuing.
        /// </summary>
        public static string ErrorWhileGiveBonus {
            get {
                return ResourceManager.GetString("ErrorWhileGiveBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error processing the reward &quot;{0}&quot;.
        /// </summary>
        public static string ErrorWhileHandleRedeem {
            get {
                return ResourceManager.GetString("ErrorWhileHandleRedeem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meme sending events found.
        /// </summary>
        public static string EventsNotFound {
            get {
                return ResourceManager.GetString("EventsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meme {0} sent by {1}.
        /// </summary>
        public static string LastMemeSentBy {
            get {
                return ResourceManager.GetString("LastMemeSentBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewarded last time:.
        /// </summary>
        public static string LastSupport {
            get {
                return ResourceManager.GetString("LastSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out of MemeAlerts?.
        /// </summary>
        public static string LogoutMemeAlertsConfirmation {
            get {
                return ResourceManager.GetString("LogoutMemeAlertsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out of Twitch?.
        /// </summary>
        public static string LogoutTwitchConfirmation {
            get {
                return ResourceManager.GetString("LogoutTwitchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmaa.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Reward.
        /// </summary>
        public static string MassReward {
            get {
                return ResourceManager.GetString("MassReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to memes.
        /// </summary>
        public static string Memes {
            get {
                return ResourceManager.GetString("Memes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points refunded.
        /// </summary>
        public static string PointsReturned {
            get {
                return ResourceManager.GetString("PointsReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☢ ATTENTION ☢ MEME INFORMATION WILL BE SENT FROM YOUR ACCOUNT, BUT MEME TITLES MAY CONTAIN PROHIBITED WORDS. THE PROGRAM HAS A SIMPLE FILTER BUILT IN, WHICH DOES NOT GUARANTEE ANYTHING, AND IF ANY, THIS MAY LEAD TO YOUR ACCOUNT BEING BLOCKED. USE AT YOUR OWN RISK!.
        /// </summary>
        public static string ProfanityInfo {
            get {
                return ResourceManager.GetString("ProfanityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty:.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshTooltip {
            get {
                return ResourceManager.GetString("RefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retrying with the Twitch nickname.
        /// </summary>
        public static string RetryWithTwitchNickname {
            get {
                return ResourceManager.GetString("RetryWithTwitchNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward all.
        /// </summary>
        public static string RewardAll {
            get {
                return ResourceManager.GetString("RewardAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward.
        /// </summary>
        public static string RewardButton {
            get {
                return ResourceManager.GetString("RewardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward last.
        /// </summary>
        public static string RewardLast {
            get {
                return ResourceManager.GetString("RewardLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} activated the &quot;{1}&quot; reward.
        /// </summary>
        public static string RewardRedeemed {
            get {
                return ResourceManager.GetString("RewardRedeemed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards.
        /// </summary>
        public static string RewardsHeader {
            get {
                return ResourceManager.GetString("RewardsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-text search for logs.
        /// </summary>
        public static string SearchForLogsTooltip {
            get {
                return ResourceManager.GetString("SearchForLogsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-text search for rewards.
        /// </summary>
        public static string SearchForRewardsTooltip {
            get {
                return ResourceManager.GetString("SearchForRewardsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-text search for supporters.
        /// </summary>
        public static string SearchForSupportersTooltip {
            get {
                return ResourceManager.GetString("SearchForSupportersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send meme with text.
        /// </summary>
        public static string SendMemeWithText {
            get {
                return ResourceManager.GetString("SendMemeWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Send meme with text&quot; reward successfully created. You can set up reward cost, icon, etc in your twitch dashboard.
        /// </summary>
        public static string SendMemeWithTextRewardSuccessfullyCreated {
            get {
                return ResourceManager.GetString("SendMemeWithTextRewardSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send random meme.
        /// </summary>
        public static string SendRandomMeme {
            get {
                return ResourceManager.GetString("SendRandomMeme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Send random meme&quot; reward successfully created. You can set up reward cost, icon, etc in your twitch dashboard.
        /// </summary>
        public static string SendRandomMemeRewardSuccessfullyCreated {
            get {
                return ResourceManager.GetString("SendRandomMemeRewardSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show meme name.
        /// </summary>
        public static string ShowLastMemeName {
            get {
                return ResourceManager.GetString("ShowLastMemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show last memer.
        /// </summary>
        public static string ShowLastMemer {
            get {
                return ResourceManager.GetString("ShowLastMemer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Show last memer&quot; reward successfully created. You can set up reward cost, icon, etc in your twitch dashboard.
        /// </summary>
        public static string ShowMemerRewardSuccessfullyCreated {
            get {
                return ResourceManager.GetString("ShowMemerRewardSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent mode.
        /// </summary>
        public static string SilentMode {
            get {
                return ResourceManager.GetString("SilentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stickers found.
        /// </summary>
        public static string StickersNotFound {
            get {
                return ResourceManager.GetString("StickersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stickers found for &quot;{0}&quot;.
        /// </summary>
        public static string StickersNotFoundByRequest {
            get {
                return ResourceManager.GetString("StickersNotFoundByRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support {0} not found.
        /// </summary>
        public static string SupporterNotFound {
            get {
                return ResourceManager.GetString("SupporterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memes for {0} not issued.
        /// </summary>
        public static string SupporterNotRewarded {
            get {
                return ResourceManager.GetString("SupporterNotRewarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporters.
        /// </summary>
        public static string Supporters {
            get {
                return ResourceManager.GetString("Supporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memes for {0} have been successfully issued in the amount of {1} pcs..
        /// </summary>
        public static string SupporterSuccessfullyRewarded {
            get {
                return ResourceManager.GetString("SupporterSuccessfullyRewarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to reward by nickname on Twitch.
        /// </summary>
        public static string TryRewardWithWrongNickname {
            get {
                return ResourceManager.GetString("TryRewardWithWrongNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to who received reward.
        /// </summary>
        public static string WhoReceived {
            get {
                return ResourceManager.GetString("WhoReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to who sent memes.
        /// </summary>
        public static string WhoSent {
            get {
                return ResourceManager.GetString("WhoSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
