// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwitchMemeAlertsAuto.Core;

#nullable disable

namespace TwitchMemeAlertsAuto.Core.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(TmaaDbContext))]
    [Migration("20260901143106_MemeHistory")]
    partial class MemeHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("TwitchMemeAlertsAuto.Core.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("TwitchMemeAlertsAuto.Core.MemeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BroadcasterUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RewardId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StickerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserInput")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StickerId");

                    b.ToTable("MemeHistories");
                });

            modelBuilder.Entity("TwitchMemeAlertsAuto.Core.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("TwitchMemeAlertsAuto.Core.StickerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("StickerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StickerId")
                        .IsUnique();

                    b.ToTable("Stickers");
                });

            modelBuilder.Entity("TwitchMemeAlertsAuto.Core.MemeHistory", b =>
                {
                    b.HasOne("TwitchMemeAlertsAuto.Core.StickerInfo", "Sticker")
                        .WithMany()
                        .HasForeignKey("StickerId");

                    b.Navigation("Sticker");
                });
#pragma warning restore 612, 618
        }
    }
}
